[package]
name = "RustChatServer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = {version="1.48.0", features=["macros","rt-multi-thread","net","sync","time","io-util","signal"]}
tokio-util = "0.7.17"
